In [1]:
import numpy as np

In [2]:
#CREATING A LIST

In [3]:
list1 = [2, 4, 6, 8]

In [4]:
#PUTTING THE LIST IN AN ARRAY NUMPY

In [5]:
array1 = np.array(list1)

In [6]:
#PRINTING ARRAY1

In [7]:
array1

array([2, 4, 6, 8])

In [8]:
#ARRAY1 HAS VALUES 2,4,6,8 BUT USING (np.zeros(4)) WE WILL INITIALISE ALL THE VALUE TO 0.

In [9]:
array1 = np.zeros(4)

In [10]:
#PRINTING ARRAY1 WHICH HAS VALUES ALL 0.

In [11]:
array1

array([0., 0., 0., 0.])

In [12]:
#CREATE AN ARRAY USING np.arange()

In [13]:
#CREATE AN ARRAY WITH VALUES FROM 0 TO 4

In [14]:
array2=np.arange(5)

In [15]:
array2

array([0, 1, 2, 3, 4])

In [16]:
# FROM START=1 TO END=8, WITH GAP=2

In [17]:
array3=np.arange(1,9,2)

In [18]:
array3

array([1, 3, 5, 7])

In [19]:
#GENETRATE THE RANDOMN VALUES

In [20]:
array4=np.random.randint(45,size=(3,2))

In [21]:
array4

array([[ 8, 30],
       [ 7,  5],
       [17, 29]])

In [22]:
#CREATING 2D ARRAY

In [23]:
array5=np.array([[1,2,3,4],[5,6,7,8]])

In [24]:
array5

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
#CREATING 2D ARRAY WITH 2 ROWS AND 3 COLUMNS FILLED WITH ZEROS

In [26]:
array6=np.zeros((2,3))

In [27]:
array6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
#CREATING 3D ARRAY WITH 2*3*4 FILLED WITH ZEROS

In [29]:
array7=np.zeros((2,3,4))

In [30]:
array7

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [31]:
 # Create a 2-D array with elements initialized to 5

In [32]:
numpy_array= np.full((2, 2), 5)

In [33]:
numpy_array

array([[5, 5],
       [5, 5]])

In [34]:
 # create a 2D array of 2 rows and 2 columns of random numbers

In [35]:
array8=np.random.rand(2,2)

In [36]:
array8

array([[0.64893197, 0.42317662],
       [0.08957269, 0.34766203]])

In [37]:
array9=np.random.rand(2,2,2)

In [38]:
array9

array([[[0.99581384, 0.47262033],
        [0.04215839, 0.6681321 ]],

       [[0.0212945 , 0.24597023],
        [0.17029053, 0.61639164]]])

In [39]:
 # create an empty 2D array with 2 rows and 2 columns

In [40]:
array10=np.empty((2,2))

In [41]:
array10

array([[0.64893197, 0.42317662],
       [0.08957269, 0.34766203]])

In [42]:
 # create an empty 3D array of shape (2, 2, 2) 

In [43]:
array11=np.empty((2,2,2))

In [44]:
array11

array([[[0.99581384, 0.47262033],
        [0.04215839, 0.6681321 ]],

       [[0.0212945 , 0.24597023],
        [0.17029053, 0.61639164]]])

In [45]:
# ndim returns number of dimension of the arraY

In [46]:
array11.ndim

3

In [47]:
# size returns number of elements in the array

In [48]:
array11.size

8

In [49]:
#shape returns the size of the array in each dimension.

In [50]:
array11.shape

(2, 2, 2)

In [51]:
#itemsize returns the size (in bytes) of each elements in the array

In [52]:
array11.itemsize

8

In [53]:
# data returns the buffer containing actual elements of the array in memory

In [54]:
array11.data

In [55]:
 # create an array of integers 

In [56]:
arr1=np.array([2,4,6])

In [57]:
arr1.dtype

dtype('int32')

In [58]:
 # convert data type of arr1 to float

In [59]:
arr2=arr1.astype('float')

In [60]:
arr2.dtype

dtype('float64')

In [61]:
arr1=arr1.astype('float')

In [62]:
arr1.dtype

dtype('float64')

In [63]:
#NUMPY INPUT OUTPUT

In [64]:
# save() = saves an array to a binary file in the NumPy .npy format.

In [65]:
arr3 = np.array([[1, 3, 5], [7, 9, 11]])

In [66]:
arr3

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [67]:
np.save('file1.npy', arr3)

In [68]:
#load() = loads data from a binary file in the NumPy .npy format

In [69]:
 loaded_array= np.load('file1.npy')

In [70]:
loaded_array

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [71]:
#savetxt() = saves an array to a text file in a specific format

In [72]:
 arr4 = np.array([[1, 3, 5], [7, 9, 11]])

In [73]:
np.savetxt('file2.txt', arr4)

In [74]:
#loadtxt() =  loads data from a text file.

In [75]:
 loaded_array= np.loadtxt('file2.txt')

In [76]:
loaded_array

array([[ 1.,  3.,  5.],
       [ 7.,  9., 11.]])

In [77]:
#NUMPY BROADCASTING

In [78]:
# AIRTHMETIC OPERATIONS

In [79]:
#ADDITION OF ARRAYS OF DIFFERENT SIZES

In [80]:
#ADDITION OF 1D ARRAY WITH 2D ARRAY

In [81]:
arr1d= np.array([1,2,3])

In [82]:
arr2d=np.array([[1],[2],[3]])

In [83]:
sum=arr1d+arr2d

In [84]:
sum

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [85]:
#MATRIX OPERATIONS

In [86]:
matrix1 = np.array([[1, 3], [5, 7]])

In [87]:
matrix1

array([[1, 3],
       [5, 7]])

In [88]:
matrix2 = np.array([[2, 3, 5], [7, 14, 21], [1, 3, 5]])

In [89]:
matrix2

array([[ 2,  3,  5],
       [ 7, 14, 21],
       [ 1,  3,  5]])

In [90]:
#Matrix Multiplication

In [91]:
mat1=np.array([[1,3],[5,7]])

In [92]:
mat2=np.array([[2,6],[4,8]])

In [93]:
result=np.dot(mat1, mat2)

In [94]:
result

array([[14, 30],
       [38, 86]])

In [95]:
#TRANSPOSE oF A MATRIX

In [96]:
result1=np.transpose(mat1)

In [97]:
result1

array([[1, 5],
       [3, 7]])

In [98]:
#NUMPY VECTORIZATION

In [99]:
arra1=np.array([1,2,3,4,5])

In [100]:
number=10

In [101]:
result2=arra1+number

In [102]:
result2

array([11, 12, 13, 14, 15])

In [103]:
#NumpyVectorization to Add Two Arrays Together

In [104]:
array1=np.array([[1,2,3],[4,5,6]])

In [105]:
array2=np.array([[11,22,33],[44,55,66]])

In [106]:
array_sum=array1+array2

In [107]:
array_sum

array([[12, 24, 36],
       [48, 60, 72]])

In [108]:
#BOOLEAN MASK

In [109]:
array1=np.array([12,23,45,21,32,45,6,78])

In [110]:
boolean_mask=array1>20

In [111]:
boolean_mask

array([False,  True,  True,  True,  True,  True, False,  True])

In [112]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [113]:
boolean_mask= array1 % 2 != 0

In [114]:
boolean_mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [115]:
 result = array1[boolean_mask]

In [116]:
result

array([1, 3, 5, 7, 9])

In [117]:
 array1 = np.array([1, 2, 4, 9, 11, 16, 18, 22, 26, 31, 33, 47, 51, 52])

In [118]:
boolean_mask= (array1 < 10) | (array1 > 40)